# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Блог Глеба Калинина
subtitle: Картография целой жизни
description:
author: Глеб Калинин
follow: Следите за моими постами
search: Поиск по блогу
facebook: kalinin
twitter: glebis
googleplus: 111301961252276698105
language: ru_RU
l10n: ru
timezone:
disqus_shortname: glebkalinin



searchid: 2103323


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://glebkalinin.ru
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

archive_generator:
  per_page: 100





# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

  английский: english
  бег: running
  бизнес: business
  безопасность: security
  блоги: blogs
  браузеры: browsers
  бренды: brands
  букмарклеты: bookmarklets
  веб: web
  веб-проекты: web-projects
  Global Shapers: global-shapers
  внимание: attention
  вопросы: questions
  восприятие: perception
  данные: data
  дебаты: debates
  деньги: money
  дизайн: design
  дизайн-мышление: design-thinking
  допреальность: dopreality
  здоровье: health
  журналистика: journalism
  идеи: ideas
  иллюзия: illusion
  инструменты: tools
  интернет: internet
  интерфейсы: interfaces
  информационная перегрузка: information-overload
  искусство: art
  исследование: research
  книги: books
  коммуникации: communications
  контент: content
  контент-стратегия: content-strategy
  красота: beauty
  лекции: lectures
  локоло: lokolo
  литература: literature
  маркетинг: marketing
  медиа: media
  медитация: meditation
  тело: body
  мозг: brain
  монетизация: monetization
  мотивация: motivation
  мышление: myishlenie
  наука: science
  некоммерческие проекты: non-commercial
  новые медиа: new-media
  образование: education
  обучение: learning
  память: memory
  письмо: writing
  поисковая оптимизация: seo
  практики: practices
  программирование: programming
  продуктивность: productivity
  психология: psychology
  публикации: publications
  публичные выступления: public-perfomances
  резиновая верстка: fluid
  реклама: ads
  риторика: rhetoric
  сайты: sites
  саморазвитие: self-development
  свобода: freedom
  сервисы: services
  события: events
  социальные сети: social-networks
  спорт: sports
  стартапы: startups
  стресс: stress
  текст: text
  телевидение: tv
  типографика: typography
  управление проектами: project-management
  устойчивое развитие: sustainability
  фиксированная верстка: fixed
  фильтрация: filters
  физиология: physiology
  ценообразование: pricing  
  читано на неделе: press-review
  чтение: reading
  шрифты: font
  экономика: economics
  эмоции: emotions
  эксперимент.ру: experiment-ru
  электронная почта: email
  эстетика:  aesthetics
  юзабилити: usability
  язык: language


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: D MMMM YYYY
time_format: HH:mm

# Pagination
## Set per_page to 0 to disable pagination
per_page: 30
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: gk

plugins:
  hexo-footnotes
  hexo-typograf




# The following settings is the quick start options.
generator_amp:
  templateDir:  amp-template
  assetDistDir: amp-dist
  logo:
    path:   sample/sample-logo.png
    width:  600
    height: 60
  substituteTitleImage: 
    path:   sample/sample-substituteTitleImage.png
    width:  1024
    height: 800
  warningLog: false   # To display warning, please set true.




feed:
  type: atom
  path: atom.xml
  limit: 20

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/glebis/glebkalinin.ru
