# Header
logo_text: # Add text logo instead of logo image
menu:
  Кто я: about/
  # Сейчас: now/
  Статьи: archives/
  Менторинг: services/
  Рассылка: subscribe/
  ТГ-канал: https://t.me/experimentally

# Content
excerpt_link: Читать далее →
fancybox: 0

# Miscellaneous
google_analytics: UA-11190202-1
favicon: /favicon.png
